[package]
edition = "2021"
authors = ["dnaq", "jedisct1"]
build = "build.rs"
description = "Maintained FFI bindings for libsodium stable"
documentation = "https://docs.rs/libsodium-sys-stable"
keywords = ["libsodium", "NaCl", "crypto", "cryptography"]
license = "MIT OR Apache-2.0"
links = "sodium"
name = "libsodium-sys-stable"
repository = "https://github.com/jedisct1/libsodium-sys-stable"
categories = ["cryptography", "api-bindings"]
version = "1.20.9"

[build-dependencies]
pkg-config = "0.3"
tar = "0.4"
libflate = "2.1"
ureq = { version = "2.10", default-features = false }
minisign-verify = "0.2"

[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"
zip = { version = "2.1", default-features = false, features = ["deflate"] }

[target.'cfg(not(target_env = "msvc"))'.build-dependencies]
cc = "1.1"

[dependencies]
libc = { version = "0.2", default-features = false }

[lib]
name = "libsodium_sys"

[features]
default = []
use-pkg-config = []
fetch-latest = []
optimized = []
minimal = []
